plugins {
    id "com.android.application"
}

android {
    namespace "com.oxguard.offlineplayer"
    compileSdk 35

    defaultConfig {
        applicationId "com.oxguard.offlineplayer"
        minSdk 23
        targetSdk 35
        versionCode 3
        versionName "1.1.0"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
